#!/bin/bash 

# Blue
i="0"
resize -s 25 80
clear
while [ $i -lt 1 ]
do
clear
ip=$(ip addr show wlan0 | awk '/inet / {print $2}' | cut -d/ -f 1)

 echo -e '\e[1;33m

            ██╗  ██████╗  ██╗     ███████╗██╗   ██╗███████╗
           ██╔╝ ██╔═████╗ ╚██╗    ██╔════╝╚██╗ ██╔╝██╔════╝
           ██║  ██║  ╔██║  ██║    █████╗   ╚████╔╝ █████╗  
           ██║  ████╔╝██║  ██║    ██╔══╝    ╚██╔╝  ██╔══╝  
           ╚██╗ ╚██████╔╝ ██╔╝    ███████╗   ██║   ███████╗
            ╚═╝  ╚═════╝  ╚═╝     ╚══════╝   ╚═╝   ╚══════╝

\e[1;34m
                                Created by "734415"
                           \e[1;31m

 EYE is intented ONLY FOR EDUCATIONAL PURPOSES!!! 

 To get a better idea of how this tool works, 'Analyse_File' in the terminal 
  
 

\e[1;32m
[1] File Analysis Options 
[2] Option 1
[3] Option 2
[4] Option 3
[5] Option 4
[6] Option 5
[7] Option 6
[8] option 7
[9] option 8
[10] option 10
[11] option 11
[12] option 12 
'
 
service postgresql start
file='1'
option1='2'
option1='3'
option1='4'
option1='5'
option1='6'
option1='7'
option1='2'
option1='8'
option1='9'
option1='10'
option1='11'
option1='12'

read x


if [ "$x" == "$file" ]; then                        #path
echo "Enter File Name (Including format e.g. doc, xlsx and pdf)" 
read r
echo -e

msfconsole -q -x  "python oledump.py $r"



elif [ "$x" == "$option1" ]; then                        #option 1
echo "Option 1 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s1 $r"'
'

elif [ "$x" == "$option2" ]; then                        #option 2
echo "Option 2 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s2 $r"'
'

elif [ "$x" == "$option3" ]; then                        #option 3
echo "Option 3 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s3 $r"'
'

elif [ "$x" == "$option4" ]; then                        #option 4
echo "Option 4 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s4 $r"'
'

elif [ "$x" == "$option5" ]; then                        #option 5
echo "Option 5 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s5 $r"'
'

elif [ "$x" == "$option6" ]; then                        #option 6
echo "Option 6 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s6 $r"'
'

elif [ "$x" == "$option7" ]; then                        #option 7
echo "Option 7 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s7 $r"'
'
elif [ "$x" == "$option8" ]; then                        #option 8
echo "Option 8 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s8 $r"'
'

elif [ "$x" == "$option9" ]; then                        #option 9
echo "Option 9 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s9 $r"'
'

elif [ "$x" == "$option10" ]; then                        #option 10
echo "Option 10 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s10 $r"'
'

elif [ "$x" == "$option11" ]; then                        #option 11
echo "Option 11 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s11 $r"'
'

elif [ "$x" == "$option12" ]; then                        #option 12
echo "Option 12 - Enter File Name (Including format e.g. doc, xlsx and pdf)"  
read r

msfconsole -q -x  "python oledump.py -s12 $r"


echo -e '\e[1;33m
 
   BlueEYE

  \e[0m



                          Press ENTER to Main Menu
'
read
else 



 
echo -e ' \e[1;31m
                                                                           
'

fi

done



